// Template de la Convention de sous-traitance d'assistance technique ADBI.
// Source unique consommee par l'apercu HTML, l'export DOCX et l'export PDF.
// Les variables sont au format {{cle}} ; le gras inline au format **texte**.
//
// TRANSCRIPTION VERBATIM du contrat ADBI fourni (Convention SUND INDUSTRY SYSTEM /
// Calvo Corentin). Le texte des articles est conserve a l'identique ; seules les
// valeurs propres a chaque contrat (societe, intervenant, dates, TJM, client final,
// lieu, contacts) sont remplacees par des variables {{cle}}.

const sousTraitance = {
  id: "sous-traitance",
  titre: "CONVENTION DE SOUS-TRAITANCE D’ASSISTANCE TECHNIQUE",
  blocks: [
    { t: "cover" },
    { t: "pagebreak" },

    // ---- Parties ----
    { t: "parties" },
    { t: "p", x: "Le Client final a lancé une consultation relative à la réalisation d’un Projet (ci-après défini)." },
    { t: "p", x: "ADBI souhaite bénéficier de l’expertise d’une entreprise extérieure en lui confiant une partie des prestations concourant à la réalisation du Projet." },
    { t: "p", x: "Le Sous-Traitant s’est déclaré (i) être parfaitement dimensionné pour répondre à l’ensemble des besoins du Client final, en termes de qualité, de fiabilité, de sécurité, de continuité, de délais et de niveaux de service, et (ii) avoir une pleine capacité de prise en charge de l’ensemble du périmètre des Prestations, notamment en termes de compétence, d’expérience, de savoir-faire et de moyens conformes aux meilleurs standards du marché." },
    { t: "p", x: "ADBI a remis une offre au Client final (ci-après l’Offre) intégrant la proposition du Sous-Traitant (ci-après la Proposition), pour réaliser des Prestations au bénéfice du Client final." },
    { t: "p", x: "L’Offre ayant été retenue par le Client final, ADBI en qualité de Sous-Traitant, a signé le Contrat Client référencé en annexe de la présente Convention." },
    { t: "p", x: "En conséquence, les Parties ont convenu d’établir la présente Convention, le dimensionnement et la capacité du Sous-Traitant à honorer l’intégralité du périmètre des Prestations confiées étant une condition essentielle à la signature de la présente Convention." },
    // La page 2 (parties + préambule) se termine ; la page 3 commence par cette phrase.
    { t: "pagebreak" },
    { t: "p", x: "**Il est exposé et convenu ce qui suit :**" },
    { t: "spacer" },

    // Le corps des articles est présenté sur deux colonnes (comme le contrat original).
    { t: "col2-start" },

    { t: "h2", x: "ARTICLE 1 – DÉFINITIONS" },
    { t: "p", x: "**« Client final »** désigne le client d’ADBI, ayant conclu un contrat avec ADBI." },
    { t: "p", x: "**« Contrat Client »** désigne le contrat (y compris ses annexes) conclu entre le Client final et ADBI relatif au Projet." },
    { t: "p", x: "**« Convention »** désigne la présente convention de prestations de service, incluant les annexes." },
    { t: "p", x: "**« Prestations »** désigne les prestations d’assistance technique confiées au Sous-traitant dans le cadre du Projet, dont le détail figure en Annexe 1 aux présentes." },
    { t: "p", x: "**« Projet »** désigne le projet confié à ADBI par le Client final, conformément au Contrat Client." },

    { t: "h2", x: "ARTICLE 2 – OBJET DU CONTRAT" },
    { t: "p", x: "Le présent contrat a pour objet de définir les conditions dans lesquelles le Sous-Traitant confie au Sous-Traitant, qui l’accepte, l’exécution des Prestations." },
    { t: "p", x: "Cette assistance technique est exclusive de toute notion de mise à disposition de personnel entrant dans le cadre du travail temporaire." },

    { t: "h2", x: "ARTICLE 3 – DOCUMENTS CONTRACTUELS – INTÉGRALITÉ" },
    { t: "p", x: "La réalisation des Prestations au titre du Projet est soumise aux termes de l’ensemble des documents contractuels suivants, à l’exclusion de tout autre :" },
    { t: "dash", x: "Le présent document," },
    { t: "dash", x: "L’Annexe 1 conditions particulières," },
    { t: "dash", x: "Le Contrat Client, le cas échéant." },
    { t: "p", x: "Dans l’hypothèse ou des difficultés d’interprétation entre les annexes et le présent document apparaitraient, ce dernier prévaut. Les documents contractuels expriment l’intégralité des obligations entre les Parties." },
    { t: "p", x: "Aucun autre document technique, publicitaire ou commercial d’aucune sorte, aucune correspondance antérieure à la signature de la présente Convention ne peut engendrer des obligations au titre de la Convention." },

    { t: "h2", x: "ARTICLE 4 – OBLIGATIONS DU SOUS-TRAITANT" },
    { t: "p", x: "Les Prestations confiées au Sous-Traitant sont décrites dans l'Annexe 1 à la Convention." },
    { t: "p", x: "Le Sous-Traitant réalise les Prestations conformément aux dispositions mentionnées à la présente Convention et conformément aux modalités et spécifications définies au Contrat Client, dont les termes, conditions, délais et niveaux de qualité et de service lui seront répercutés pour les stipulations de ce dernier concernant les travaux sous traités." },
    { t: "p", x: "Le Sous-Traitant s’engage également à réaliser les prestations sous traitées de telle sorte que le Sous-Traitant puisse exécuter ses propres obligations conformément au Contrat Client." },
    { t: "p", x: "Le Sous-Traitant s’engage à mettre en place les moyens matériels et humains nécessaires à la bonne exécution des Prestations et à informer le Sous-Traitant de tout événement qui pourrait perturber la réalisation de la Prestation et dont il aurait connaissance." },
    { t: "p", x: "Le Sous-Traitant est tenu d’établir un compte rendu d’activité et de le transmettre mensuellement au Sous-Traitant." },
    { t: "p", x: "Le Sous-Traitant s’engage à assurer le support et la garantie de ses prestations selon les modalités prévues à l'Article 10 de la présente Convention." },
    { t: "p", x: "De surcroît, le Sous-Traitant s’engage à :" },
    { t: "dash", x: "N’affecter aux prestations sous traitées que des personnels suffisamment qualifiés et compétents pour en assurer la bonne exécution," },
    { t: "dash", x: "Solliciter auprès du Sous-Traitant les informations pouvant se révéler nécessaires à la bonne exécution des prestations sous traitées," },
    { t: "dash", x: "Exercer auprès du Sous-Traitant une action de conseil et de mise en garde relativement aux prestations sous traitées, conformément aux normes et usages en vigueur dans la profession," },
    { t: "dash", x: "Participer à l’organisation et au fonctionnement des organes de suivi des prestations sous traitées," },
    { t: "dash", x: "Tenir le Sous-Traitant régulièrement informé des événements ou circonstances affectant, le cas échéant, le contenu, le planning, la continuité, la qualité ou le prix des prestations sous traitées," },
    { t: "dash", x: "Documenter selon l’état de l’art l’ensemble des prestations effectuées afin d’en garantir l’évolutivité et la maintenabilité fonctionnelle et technique par un tiers quelconque." },

    { t: "h2", x: "ARTICLE 5 – CONCOURS DU SOUS-TRAITANT" },
    { t: "p", x: "Le Sous-Traitant s’engage à :" },
    { t: "dash", x: "fournir au Sous-Traitant les informations et documents nécessaires à la réalisation des Prestations," },

    { t: "h2", x: "ARTICLE 6 – LIEU D’EXÉCUTION DES PRESTATIONS" },
    { t: "p", x: "Les Prestations sont exécutées dans les lieux définis en Annexe 1 à la présente Convention." },
    { t: "p", x: "Dans le cas où les Prestations sont exécutées dans les locaux du Sous-Traitant et/ou du Client final, les personnels du Sous-Traitant appliquent la politique de sécurité, le règlement, les horaires et les consignes en vigueur dans lesdits locaux qui lui ont été préalablement communiqués par le Sous-Traitant." },

    { t: "h2", x: "ARTICLE 7 – CONDITIONS FINANCIÈRES" },
    { t: "p", x: "En contrepartie de l’exécution de l’ensemble des Prestations, le Sous-Traitant versera au Sous-Traitant une rémunération établie sur la base du temps passé et selon le tarif défini en Annexe 1." },
    { t: "p", x: "Les prix s'entendent hors taxes et correspondent au coût total des Prestations, y compris les droits cédés par le Sous-Traitant conformément à l'Article 9 de la présente Convention. Cette rémunération est réputée couvrir toute dépense résultant de la nature des Prestations et de leurs conditions d’exécution." },
    { t: "p", x: "Le Sous-Traitant communiquera chaque mois au Sous-Traitant un récapitulatif des travaux effectués sur la base du temps passé." },
    { t: "p", x: "Toutes les factures doivent être établies en double exemplaires et adressées à l’adresse suivante par mail : {{comptaEmail}}" },
    { t: "p", x: "{{comptaContact}}" },
    { t: "p", x: "{{comptaTel}}" },
    { t: "p", x: "accompagnées des éléments suivants :" },
    { t: "dash", x: "un compte rendu d’activité signé par le Client final," },
    { t: "dash", x: "les références de la présente Convention," },
    { t: "dash", x: "les références de la commande ou du Contrat Client." },
    { t: "p", x: "Les factures sont payables {{delaiPaiement}} jours dès réception des factures, sous réserve de leur conformité aux prescriptions qui précèdent." },
    { t: "p", x: "Le Sous-Traitant reconnaît et accepte que seules les Prestations fournies dans le respect des conditions convenues, donneront lieu à paiement au prix convenu. Par conséquent, le Sous-Traitant se réserve le droit de retenir la part du paiement correspondant en informant formellement le Sous-Traitant, par mail avec accusé de réception ou par lettre recommandée avec accusé de réception, des motifs le justifiant." },

    { t: "h2", x: "ARTICLE 8 – PROPRIÉTÉ" },
    { t: "p", x: "Le Sous-Traitant cède l’ensemble de ses droits de propriété intellectuelle concernant l’ensemble des documents et programmes réalisés spécifiquement pour le Sous-Traitant dans le cadre de la Convention, notamment les droits de reproduction, utilisation, correction concernant les développements spécifiques, les analyses, les interfaces, les adaptations, les outils des développements et plus généralement des travaux réalisés spécifiquement pour le Sous-Traitant dans le cadre des présentes." },
    { t: "p", x: "Au titre de la cession des droits d’auteur, le Sous-Traitant cède au Sous-Traitant pour toute exploitation et sur tout support présent et à venir, notamment papier, magnétique, optique ou vidéographique, disques, disquettes, bandes, listings, internet, intranet, les droits relatifs aux développements spécifiques et livrables réalisés au titre des présentes ainsi que les droits de reproduction et utilisation, représentation, publication, édition, adaptation, modification, correction, développement, intégration, transcription, traduction, numérisation." },
    { t: "p", x: "Cette cession est effective tant pour la France que pour l’étranger et pour toute la durée du droit d’auteur." },
    { t: "p", x: "Les outils de développement, apportés par le Sous-Traitant et mis en œuvre au titre de la Convention, restent la propriété du Sous-Traitant." },

    { t: "h2", x: "ARTICLE 9 – ASSURANCES ET RESPONSABILITÉ" },
    { t: "p", x: "Chacune des Parties s'engage à être titulaire d'une police d'assurance auprès d'une compagnie notoirement solvable couvrant les conséquences pécuniaires de sa responsabilité civile et professionnelle, dans le cas où celle-ci serait engagée." },
    { t: "p", x: "Le Sous-Traitant assume l’entière responsabilité quant à la réalisation de l’ensemble des Prestations. Le Sous-Traitant s’engage à exécuter les obligations contractuelles à sa charge avec tout le soin possible et à se conformer aux règles en usage dans sa profession au moment et pour le type de prestation effectuée. Le Sous-Traitant est responsable de toute inexécution ou mauvaise exécution de ses obligations aux termes de la présente Convention." },
    { t: "p", x: "En outre, le Sous-Traitant s’engage à garantir le Sous-Traitant contre tout recours de quelque nature que ce soit ayant pour origine tout manquement, ou toute inexécution ou mauvaise exécution par le Sous-Traitant de ses obligations aux termes de la Convention." },
    { t: "p", x: "Aucune des Parties ne saurait être tenue responsable envers l’autre au titre de la présente Convention, pour des dommages indirects." },

    { t: "h2", x: "ARTICLE 10 – DÉFAILLANCE" },
    { t: "p", x: "Si après une mise en demeure par lettre recommandée avec accusé de réception restée huit (8) jours sans effet, le Sous-Traitant pour quelque raison que ce soit, manquait à ses obligations contractuelles, ce dernier sera considéré comme défaillant." },
    { t: "p", x: "Les Prestations qui lui ont été confiées au tire de la présente Convention pourront, au choix du Sous-Traitant, soit être reprise par le Sous-Traitant, soit être confiée par lui à une société tierce, sans préjudice de la possibilité de résilier la Convention conformément à l’Article 18 des présentes." },
    { t: "p", x: "Le Sous-Traitant devra supporter les conséquences de toute augmentation du coût de ses prestations qui pourrait résulter de sa défaillance, ainsi que de tous les préjudices tels que notamment frais supplémentaires ou pénalités de retard, conformément à l’Article 11 des présentes." },

    { t: "h2", x: "ARTICLE 11 – CONFIDENTIALITÉ" },
    { t: "p", x: "Toutes informations de quelque nature qu’elles soient, commerciales ou techniques, divulguées par le Client au Sous-Traitant (ou dont le Sous-Traitant ou son personnel viendrait à prendre connaissance) à l’occasion de la conclusion du Contrat ou au cours de son exécution, restent la propriété exclusive du Client (l’« Information Confidentielle »). Le Sous-Traitant en fera usage que dans le cadre du Contrat et pour les besoins des Services, et les retournera au Client après résiliation ou expiration du Contrat. Le Sous-Traitant s’engage à tenir ces informations strictement confidentielles pendant la durée du Contrat et une période de 5 ans après son expiration ou résiliation, à les communiquer uniquement aux employés ou conseils qui doivent en avoir connaissance pour l’exécution du Contrat et qui sont tenus de les traiter confidentiellement (ce dont le Sous-Traitant se porte fort) et à ne les communiquer en aucun cas à des tiers sans avoir obtenu l’accord écrit préalable du Client." },
    { t: "p", x: "L’obligation de confidentialité ne s’applique pas aux informations fournies par le Client qui sont déjà dans le domaine public et/ou qui ont été obtenues légitimement par le Sous-Traitant auprès de tiers ayant le droit de divulguer ces informations." },
    { t: "p", x: "Sauf accord écrit et préalable du Client, le Sous-Traitant s’interdit de communiquer, de quelque manière que ce soit, sur l’existence et la teneur de relations commerciales entre le Client ou son groupe en général d’une part et le Sous-Traitant d’autre part. En particulier, ni le Sous-Traitant ni le personnel désigné par celui-ci pour l’exécution des prestations ne sont autorisés à se prévaloir à l’égard de tiers de l’exécution des prestations ou d’utiliser le nom ou la marque « {{clientFinal}} » ou d’y faire référence, à des fins commerciales, privées ou autres." },
    { t: "p", x: "Il est convenu entre les Parties qu’aucun droit de propriété intellectuelle ou industrielle n’est transféré, cédé, concédé ou accordé par le Client au Sous-Traitant relativement aux Informations Confidentielles, outre ceux strictement nécessaire à la réalisation des Services. En conséquence, le Sous-Traitant s’interdit notamment d’exploiter ou d’utiliser sous quelque forme que ce soit tout ou partie des Informations Confidentielles pour d’autres Clients, sauf accord préalable et écrit du Client." },
    { t: "p", x: "L’ensemble des Informations Confidentielles communiquées par le Client au Sous-Traitant (ou dont le Sous-Traitant ou son personnel viendrait à prendre connaissance) est et restera la propriété exclusive du Client. A première demande du Client ou au terme du Contrat, le Sous-Traitant s’engage dans le délai de quinze (15) jours :" },
    { t: "li", x: "Soit à restituer au Client l’intégralité des Informations Confidentielles en sa possession, ainsi que toutes reproductions, copies et extraits de ces Informations Confidentielles ;" },
    { t: "li", x: "Soit et seulement si le Client exprime ce choix, à procéder à la destruction immédiate de toutes les Informations Confidentielles encore en sa possession, ainsi que de toutes copies et extraits contenant de telles Informations Confidentielles et à communiquer au Client une attestation écrite de cette destruction signée par un représentant dûment autorisé." },

    { t: "h2", x: "ARTICLE 12 – PERSONNEL DU SOUS-TRAITANT – OBLIGATIONS SOCIALES" },
    { t: "p", x: "Le personnel du Sous-Traitant dédié à l’exécution des Prestations demeurera pendant toute la durée de la Convention sous l’entière autorité hiérarchique et disciplinaire du Sous-Traitant qui en assurera seul la gestion administrative, comptable et sociale." },
    { t: "p", x: "Les collaborateurs du Sous-Traitant ne pourront ni agir, ni être réputés agir, en tant que salariés du Sous-Traitant ou du Client final, à quelque fin que ce soit." },
    { t: "p", x: "A ce titre, le Sous-Traitant disposera de son personnel lorsque la législation du travail l’impose. Il en est de même quand l’accomplissement normal de leur contrat de travail nécessite la présence des salariés du Sous-Traitant dans les locaux de celui-ci, par exemple pour les nécessités de la formation ou la participation à la vie sociale du Sous-Traitant." },
    { t: "p", x: "Le Sous-Traitant garantit la régularité de sa situation dans le cadre de la Convention, notamment à l’égard de toutes les administrations et autorités fiscales et au regard la loi du 11 mars 1997 relative à la lutte contre le travail illégal et de toutes les obligations légales à sa charge à l’égard des administrations sociales et fiscales." },
    { t: "p", x: "A ce titre, le Sous-Traitant certifie notamment, avoir procédé aux immatriculations légales et aux déclarations sociales et fiscales obligatoires, auprès des organismes compétents, notamment, de sécurité sociale et de l’administration fiscale, conformément, en particulier, aux dispositions des articles L.8221-3 et L.8221-5, L 143-3 et L 1221-10, L1221-13 et L1221-15 du code du travail." },
    { t: "p", x: "En application des articles L.8221-3 à 8225-5 du Code du travail, le Sous-Traitant remet au Sous-Traitant à compter de la signature de la Convention et tous les six mois au cours de son exécution, les documents ci-après :" },
    { t: "dash", x: "Une attestation de fourniture de déclarations sociales émanant de l’organisme de protection sociale chargé du recouvrement des cotisations et des contributions sociales lui incombant et datant de moins de six mois," },
    { t: "dash", x: "Une attestation sur l’honneur du dépôt auprès de l’administration fiscale, à la date de l’attestation, de l’ensemble des déclarations fiscales obligatoires," },
    { t: "dash", x: "un extrait K-bis datant de moins de 6 mois," },
    { t: "dash", x: "dans la mesure où le Sous-Traitant emploie des salariés, une attestation sur l’honneur, de la réalisation du travail par des salariés employés régulièrement au regard des articles L320 du Code du Travail modifiés." },

    { t: "h2", x: "ARTICLE 13 – NON-SOLLICITATION RÉCIPROQUE DE PERSONNEL" },
    { t: "p", x: "Chaque partie s’engage vis-à-vis de l’autre, à ne pas débaucher, embaucher ou faire travailler de manière directe et indirecte, toute personne ayant participé à la réalisation des travaux demandés, pendant toute la durée du contrat." },
    { t: "p", x: "Dans le cas où l’une des Parties ne respecterait pas cet engagement, elle s’engage à dédommager l’autre Partie en lui versant sans délai une somme égale à {{dureeNonSollicitation}}." },

    { t: "h2", x: "ARTICLE 14 – EXCLUSIVITÉ" },
    { t: "p", x: "Pendant toute la durée de la présente Convention et {{dureeExclusivite}} après la fin de celle-ci, le Sous-Traitant s’engage à ne pas contracter directement ou indirectement avec pour ce qui concerne l’objet du Contrat Client." },
    { t: "p", x: "Dans ce cadre, le Sous-Traitant s’engage à s’abstenir de toute liaison directe avec le Client final sans avoir au préalable obtenu l’accord du Sous-Traitant et de manière générale, le Sous-Traitant s’interdit d’effectuer toutes démarches susceptibles d’être interprétées par le Client final ou par le Sous-Traitant comme une proposition ou un souhait de reprendre pour son compte des engagements souscrits par le Sous-Traitant envers le Client Final au terme du Contrat Client." },
    { t: "p", x: "Au cas où cette disposition ne serait pas respectée, le Sous-traitant s'engage à verser à ADBI une indemnité égale à 12 mois de chiffres d’affaires calculé sur la base du montant des prestations facturées en violation des engagements pris et sans préjudice de tous dommages-intérêts, préjudices et frais." },
    { t: "p", x: "Le Sous-traitant s'interdit également toute action pouvant nuire à l'image de marque d’ADBI." },

    { t: "h2", x: "ARTICLE 15 – CESSION DU CONTRAT – SOUS-TRAITANCE" },
    { t: "p", x: "La présente Convention ne peut en aucun cas faire l’objet d’une cession totale ou partielle, à titre onéreux ou gracieux, par l’une ou l’autre des parties au profit d’un tiers." },
    { t: "p", x: "Le Sous-Traitant s’interdit de sous-traiter les travaux prévus sans l’accord exprès et préalable du Sous-Traitant." },

    { t: "h2", x: "ARTICLE 16 – INDÉPENDANCE" },
    { t: "p", x: "Les Parties déclarent également en tant que de besoin que la Convention exclut expressément de leur part toute volonté de conclure, sous quelque forme que ce soit, un contrat ayant pour caractéristique de constituer entre elles une hiérarchie ou d’établir un quelconque lien de subordination de l’une à l’égard de l'autre des parties ou du personnel de l’une des parties envers l’autre partie ou son personnel." },
    { t: "p", x: "Aucune des parties n’est autorisée à conclure un quelconque engagement pour le compte ou au nom de l’autre partie." },

    { t: "h2", x: "ARTICLE 17 – DURÉE" },
    { t: "p", x: "La présente Convention prend effet à compter de sa signature par les Parties, et est conclue pour la durée du Contrat Client, sous réserve de disposition contraire en Annexe 1." },
    { t: "p", x: "La date de démarrage des Prestations est précisée en Annexe 1." },
    { t: "p", x: "La présente Convention ne saurait faire l’objet d’une tacite reconduction. Elle ne pourra être renouvelée ou prolongée que par voie d’avenant dûment signé par les Parties." },

    { t: "h2", x: "ARTICLE 18 – RÉSILIATION" },
    { t: "h3", x: "18.1 Résiliation pour cause de cessation du Contrat Client" },
    { t: "p", x: "La présente Convention pourra être résiliée par le Sous-Traitant en cas de résiliation du Contrat Client, avec effet immédiat à compter de la date de réception par le Sous-Traitant d’une lettre recommandée du Sous-Traitant à cet effet. Le Sous-Traitant s'engage à remettre immédiatement à ADBI tous les éléments relatifs à l'exécution de la présente Convention, encore en sa possession, dans l'état où ces éléments sont à la date de résiliation." },
    { t: "h3", x: "18.2 Résiliation pour convenance" },
    { t: "p", x: "La présente Convention peut être résiliée, par les deux parties de plein droit et sans formalité judiciaire, par le Sous-Traitant à l’expiration d’un délai de trente (30) jours à compter de la date d’envoi par le Sous-Traitant au Client d’une lettre recommandée à cet effet." },
    { t: "p", x: "Le délai de préavis sera de trente (30) jours." },
    { t: "h3", x: "18.3 Résiliation pour faute" },
    { t: "p", x: "En cas de non-respect par l’une ou l’autre des Parties des obligations prévues à la présente Convention, et après mise en demeure par lettre recommandée avec accusé réception de l’une des Parties à l’autre restée infructueuse pendant un délai de (15) jours, la Convention pourra être résiliée par la Partie demanderesse et ce indépendamment de tous dommages intérêts qui pourraient être dûs par la Partie fautive du fait des manquements sus visés." },
    { t: "p", x: "Dans tous les cas de résiliation définis à la présente Convention, le Sous-Traitant s’engage à effectuer la réversibilité des Prestations afin de permettre au Sous-Traitant, sans difficulté, de reprendre ou de faire reprendre par un tiers désigné par lui, la fourniture desdites Prestations, et ce, dans les meilleures conditions." },

    { t: "h2", x: "ARTICLE 19 – DROIT APPLICABLE – LITIGES" },
    { t: "p", x: "La présente Convention est soumise à la loi française." },
    { t: "p", x: "En cas de litige et après une tentative de recherche d’une solution amiable, compétence expresse est attribuée au Tribunal de Commerce de {{tribunal}}." },

    { t: "h2", x: "ARTICLE 20 – DISPOSITIONS GÉNÉRALES" },
    { t: "p", x: "La Convention et ses annexes ne peuvent être modifiées que par avenant signé des deux Parties." },
    { t: "p", x: "Si l'une quelconque des stipulations, non substantielle, de la Convention est nulle, au regard d'une règle de droit en vigueur ou d'une décision judiciaire devenue définitive, elle est réputée non écrite, mais les autres stipulations gardent toute leur force et leur portée." },
    { t: "p", x: "En cas de difficulté d’interprétation entre l’un quelconque des titres et l’une quelconque des clauses de la Convention, les titres seront déclarés inexistants." },
    { t: "p", x: "Le fait, par l'une des Parties, de ne pas se prévaloir d'un manquement de l'autre Partie, à l'une quelconque des obligations visées dans les présentes, ne saurait être interprété pour l'avenir comme une renonciation à exiger le respect de l'obligation enfreinte." },
    { t: "p", x: "Le Client se réserve le droit de modifier les Conditions Générales à tout moment. Les Conditions Générales entrent en vigueur dès qu’elles sont notifiées aux Sous-Traitants. Elles s’appliquent de façon automatique à chaque Contrat ou renouvellement de Contrat conclu après les modifications notifiées au Sous-Traitant." },

    { t: "h2", x: "ARTICLE 21 – PROPRIÉTÉ" },
    { t: "p", x: "Le Sous-Traitant s’engage à n’utiliser les outils de toutes natures et logiciels mis à sa disposition par le Client que dans le seul cadre de l’exécution du Contrat, afin de réaliser les Services convenus et à ne procéder à aucune copie non autorisée, étant précisé que la mise à disposition de tout programme ou logiciel par le Client au Sous-Traitant n’entraine aucun transfert de droits de quelque nature que ce soit au-delà de ceux strictement nécessaires à la stricte réalisation des Services." },
    { t: "p", x: "En application notamment du Code de la Propriété Intellectuelle, la cession concerne les droits de reproduction, de représentation des rapports, études et de la documentation ainsi que les droits de reproduction, de représentation, d’intégration en tout ou en partie avec ou sans modification, d’interfaces, d’adaptation, de modification, de maintenance, de diffusion directe ou par satellite, d’édition, de traduction, d’arrangement, de corrections des erreurs, de décompilation, des sources et des exécutables des progiciels sur tout support et notamment support papier, disque, disquette, bande, CD ROM, pouvant être utilisés en l’état ou intégrés, avec ou sans modification tant en France qu’à l’étranger dans le monde entier." },
    { t: "p", x: "La cession porte également sur toutes les instructions pour la formation éventuelle et les supports de cours correspondants. La cession porte sur toutes ces œuvres dans toutes les versions, perfectionnées et/ou évoluées qu’elles soient achevées ou inachevées. Cette cession est faite pour tout mode d’exploitation et pour tout domaine d’application. Cette cession est faite pour la durée de protection des droits d’auteur." },
    { t: "p", x: "Au terme de cette cession, le Sous-Traitant ne dispose plus d’aucun droit patrimonial sur les rapports, les logiciels, les documentations et tous les éléments réalisés dans le cadre du Contrat." },
    { t: "p", x: "Le transfert de propriété aura lieu, au profit du Client, au fur et à mesure de la réalisation des prestations. Toutefois, en cas de résiliation anticipée du Contrat, quelle qu’en soit la cause, la cession se produira au profit du Client à la date de résiliation." },

    { t: "h2", x: "ARTICLE 22 – RÉVERSIBILITÉ DES PRESTATIONS" },
    { t: "p", x: "En cas de résiliation anticipée ou d’arrivée à échéance du Contrat pour quelque raison que ce soit le Sous-Traitant et le Client s’engagent à coopérer de bonne foi afin d’assurer, à la demande du Client, la reprise des Services soit par le Client, soit par un tiers désigné par ce dernier pour assurer la poursuite des Services. Le Sous-Traitant s’engage ainsi à apporter au Client ou à tout tiers désigné par ce dernier, son assistance technique, notamment par le transfert des informations nécessaires, pour faciliter la reprise des Services confiées. Outre les obligations de restitution des Informations Confidentielles mentionnées à l’Article 11 des présentes, le Sous-Traitant s’engage notamment à délivrer au Client, sans coût supplémentaire pour celui-ci, toutes les informations nécessaires lui permettant de préparer la réversibilité des Services." },

    { t: "h2", x: "ARTICLE 23 – GARANTIE D’ÉVICTION" },
    { t: "p", x: "Le Sous-Traitant garantit au Client la jouissance paisible de l’ensemble des Services et livrables et de toutes leurs évolutions réalisées dans le cadre du Contrat. Le Sous-Traitant garantit que tout ou partie des Services ou livrables cédés au titre du Contrat n’est grevé à quelque titre que ce soit de droits de tiers empêchant l’exécution du Contrat et l’exploitation des Services par le Client et ne constitue pas une violation de droits de propriété intellectuelle de tiers, ni un quelconque fait de concurrence déloyale ou parasitaire. En cas de réclamation, d’action ou de revendication de quelque nature que ce soit d’un tiers alléguant que tout ou partie de ces éléments ou certaines de leurs caractéristiques portent atteinte à leurs droits, le Sous-Traitant prendra à sa charge l’intégralité des sommes auxquelles le Client pourrait être condamné ou que ce dernier pourrait devoir pour quelque motif que ce soit. A ce titre, il s’engage à assurer la défense du Client en intervenant à toute instance pour le mettre hors de cause et à en supporter tous les frais et dépenses, y compris les frais de justice et les honoraires d’avocats, ainsi que tous dommages et intérêts auxquels pourrait être condamné le Client au titre d’une décision de justice ou d’une transaction et à indemniser le Client de tout autre préjudice qui pourrait résulter d’une telle action." },

    { t: "h2", x: "ARTICLE 24 – ENGAGEMENTS ET GARANTIES DU SOUS-TRAITANT" },
    { t: "p", x: "Le Sous-Traitant s’engage à apporter tous ses efforts et tous ses soins à l’exécution de la mission qui lui est confiée. Plus spécifiquement, le Sous-Traitant s’engage à fournir les Services aux lieux/dates/délais indiqués dans les Conditions Particulières. Les Services fournis doivent être strictement conformes en qualité et en quantité aux termes des Conditions Particulières ainsi qu’aux caractéristiques convenues entre les Parties." },
    { t: "p", x: "Le Sous-Traitant garantit que sa prestation de Services est conforme aux prescriptions légales et réglementaires en vigueur. Il est responsable du respect par son personnel des règles déontologiques du Client applicables aux tiers qui interviennent en son établissement. Il s’engage à ce que son personnel reconnaisse la prise de connaissance de ces règles déontologiques et qu’il s’y conforme. Les règles déontologiques sont annexées aux présentes conditions générales, elles peuvent être modifiées de façon unilatérale par le Client. Le Sous-Traitant sera immédiatement informé des modifications faites aux règles déontologiques." },
    { t: "p", x: "Dans le cadre de l’exécution du Contrat, le Sous-Traitant est tenu à un devoir général d’information, de conseil, voire de mise en garde à l’égard du Client. Au jour de la signature du Contrat, le Sous-Traitant garantit au Client qu’il dispose :" },
    { t: "li", x: "D’une vision suffisamment claire, précise et cohérente du cadre de réalisation des Services ainsi que des besoins et objectifs du Client ; et" },
    { t: "li", x: "De toutes les compétences techniques nécessaires pour l’exécution des Services." },
    { t: "p", x: "Le Sous-Traitant s’engage à réaliser les Prestations avec toute la diligence et le professionnalisme requis et à faire ses meilleurs efforts pour collaborer, le cas échéant, avec tous tiers désigné par le Client." },
    { t: "p", x: "Le Sous-Traitant s’engage également à :" },
    { t: "li", x: "Exécuter les Services conformément à l’état de l’art et de la technique ;" },
    { t: "li", x: "Fournir des Services cohérents et compatibles entre eux, ainsi qu’avec les applications et systèmes d’informations du Client ; et" },
    { t: "li", x: "Fournir des prestations documentées, de telle sorte que le Client puisse en assurer la reprise et qu’il soit en mesure d’assurer la maintenance de ses applications ou systèmes ou de les faire évoluer ou de les adapter en cohérences avec les prestations." },
    { t: "p", x: "A la fin de chaque mois ou en fin de mission, le Sous-Traitant soumet au visa du responsable désigné par le Client un « compte rendu mensuel d’activité », mentionnant les travaux réalisés dans le mois. Ce responsable pourra faire par écrit toutes les observations sur les prestations exécutées par le Sous-Traitant (planning, qualité du travail, esprit d’équipe, etc.)." },
    { t: "p", x: "Le suivi de la relation contractuelle sera assuré dans le cadre de réunions entre le Client et le Sous-Traitant, étant précisé que toute réunion de cette instance de gouvernance devra faire l’objet d’un compte-rendu écrit, rédigé par le Sous-Traitant, signé par les parties et dûment conservé par chacune parties. Les Parties désigneront chacune dans le cadre des Conditions Particulières un responsable du suivi des prestations. Les responsables du suivi des prestations se réuniront selon une périodicité mensuelle ou sur demande motivée de l’une des parties chaque fois que nécessaire afin de gérer toute requête exceptionnelle ou toute difficulté technique majeure. Lors de leurs réunions, les responsables du suivi des prestations veilleront notamment (i) à l’examen du compte rendu mensuel d’activité ; et (ii) au suivi de l’avancement des prestations." },
    { t: "p", x: "Le Sous-Traitant garantit que sa prestation de Services est conforme aux prescriptions légales et réglementaires en vigueur. Il s’engage à respecter et à faire respecter par son personnel au sein des locaux de {{clientFinal}} les règlements concernant l’hygiène et la sécurité, ainsi que toutes autres consignes et obligations visées par le règlement intérieur, le code de déontologie, notamment en matière de transactions personnelles, ou tout autre document applicable dont le personnel du Sous-Traitant exécutant la prestation devra prendre connaissance avant de débuter la mission." },
    { t: "p", x: "Le personnel désigné par le Sous-Traitant pour l’exécution des prestations est tenu de strictement limiter aux besoins liés à l’exécution des prestations, l’usage d’Internet et des systèmes informatiques mis éventuellement à disposition par {{clientFinal}}." },
    { t: "p", x: "Le personnel du Sous-Traitant devra en outre, sauf autorisation préalable du Client, se conformer aux horaires d’ouverture du site sur lequel il est tenu d’exécuter sa mission. Le personnel du Sous-Traitant devra se conformer aux horaires déterminés par le Sous-Traitant et acceptés par le Client." },
    { t: "p", x: "Le personnel du Sous-Traitant ne devra pas commettre d’agissements susceptible de porter préjudice au Client et sera tenu par une obligation de non-dénigrement du Client." },
    { t: "p", x: "En cas de résiliation anticipée ou d’arrivée à échéance du Contrat pour quelque raison que ce soit le Sous-Traitant et le Client s’engagent à coopérer de bonne foi afin d’assurer, à la demande du Client, la reprise des Services soit par le Client, soit par un tiers désigné par ce dernier pour assurer la poursuite des Services. Le Sous-Traitant s’engage ainsi à apporter au Client ou à tout tiers désigné par ce dernier, son assistance technique, notamment par le transfert des informations nécessaires, pour faciliter la reprise des Services confiées. Outre les obligations de restitution des Informations Confidentielles mentionnées à l’Article 11 des présentes, le Sous-Traitant s’engage notamment à délivrer au Client, sans coût supplémentaire pour celui-ci, toutes les informations." },

    { t: "h2", x: "ARTICLE 25 – ABSENCES, RETARD ET NON-CONFORMITÉ" },
    { t: "p", x: "Dès que possible et le cas échéant au moins trente (30) jours avant la date prévue du début de l’absence, le Sous-Traitant devra informer le Client ses absences programmées ou des congés et RTT posés par le personnel exécutant les prestations. En outre, le Sous-Traitant devra dès que possible informer le Client des arrêts maladie et autre absence du personnel exécutant les prestations." },
    { t: "p", x: "En cas d’absence prolongée du personnel exécutant les prestations, {{clientFinal}} et le Sous-Traitant conviennent de définir les modalités de son remplacement temporaire ou définitif. Le Sous-Traitant disposera d’un délai de quinze (15) jours calendaires pour proposer au Client un candidat au remplacement qui doit présenter des compétences équivalentes que le personnel devenu indisponible, étant précisé que le Client pourra, agissant de manière raisonnable, refuser le candidat remplaçant proposé. A défaut de remplacement dans ce délai (y compris lorsque le candidat remplaçant n’emporte pas l’approbation du Client), ce dernier pourra de plein droit et sans délai résilier le Contrat à la date de début de l’absence du personnel." },
    { t: "p", x: "Lorsque le Sous-Traitant a l’obligation de délivrer au Client une prestation prédéfinie, en cas de retard prévisible ou de livraison partielle, le Sous-Traitant doit immédiatement informer le Client de la date effective de réalisation de la prestation de Services, en précisant les motifs de ce retard ou de la livraison partielle, et en proposant les mesures correctives appropriées, lesquelles peuvent être refusées par le Client." },
    { t: "p", x: "Lorsque le Sous-Traitant a l’obligation de délivrer au Client une prestation prédéfinie, le Sous-Traitant s’engage à remédier, à ses frais et risques, à toute non-conformité affectant la prestation de Services au plus tard dans un délai de sept (7) jours à compter de la réception de la demande du Client. Passé ce délai, en cas de demande infructueuse, le Client peut exécuter lui-même ou faire exécuter par un tiers, aux frais et risques du Sous-Traitant (notamment coûts de déplacement, de transport, des pièces et de la main d’œuvre), les prestations requises pour pallier sa défaillance." },

    { t: "h2", x: "ARTICLE 26 – ENCADREMENT" },
    { t: "p", x: "Le Sous-Traitant exerce son activité sans aucun lien de subordination à l’égard du Client, en tant que Sous-Traitant indépendant. L’ensemble du personnel du Sous-Traitant qui sera affecté en tout ou partie à l’exécution de la mission reste, en toute circonstance, sous l’autorité hiérarchique et disciplinaire du Sous-Traitant. En toutes hypothèses et en particulier en cas d’intervention de personnels du Sous-traitant sur les sites du Client, le Sous-Traitant conserve et exerce ainsi seul les pouvoirs de direction, surveillance et de contrôle sur l’ensemble des préposés qu’il affecte à la réalisation de la prestation. Le Sous-Traitant fait donc son affaire personnelle et est seul responsable de la gestion administrative des collaborateurs qu’il affecte à la mission, sans que le Client ne puisse être inquiété de quelque manière que ce soit." },
    { t: "p", x: "Le Sous-Traitant déclare que le personnel affecté aux prestations objet du Contrat, sera régulièrement employé par lui au regard des articles du Code du Travail en vigueur en France ou de toute législation locale applicable au Client et au Sous-Traitant et s’engage à assurer, en sa qualité d’employeur, la gestion administrative, comptable et sociale de son personnel. Sauf contre-indication expresse devant figurer dans les Conditions Particulières, il est entendu que le Sous-Traitant mettra à disposition du Client uniquement du personnel ayant la qualité de salariés du Sous-Traitant." },
    { t: "p", x: "En particulier, le Sous-Traitant garantit le respect de la législation sociale en matière d’embauches de son personnel amené à intervenir au profit du Client ainsi que la régularité de sa situation en ce qui concerne le paiement de ses cotisations aux organismes sociaux. Le Sous-Traitant atteste sur l’honneur s’être acquitté de toutes ses obligations au regard des articles L.1221-10 et s., L.3243-1 et s., L.5221-8 et s., L.8221-1 et s., L.8251-1 et R.3243-1 du Code du Travail. En outre, le Sous-Traitant garantit, via la fourniture d’une attestation du Sous-Traitant au Client, la régularité des ressources internationales utilisées pour tout ou partie des prestations, notamment au regard des visas de travail, conformément aux législations sociales applicables et aux stipulations des présentes Conditions Générales." },
    { t: "p", x: "Le Sous-Traitant s’engage à ce titre, avant l’arrivée de ses collaborateurs de nationalité étrangère, dans les locaux du Client, à fournir audit Client les informations suivantes :" },
    { t: "li", x: "nom des collaborateurs," },
    { t: "li", x: "nationalité," },
    { t: "li", x: "n° d’ordre et type du titre valant autorisation de travail en France," },
    { t: "li", x: "durée de validité." },
    { t: "p", x: "Le Sous-Traitant garantit également la véracité et l’exactitude des références de son personnel affecté aux prestations objet du Contrat, en ce qui concerne notamment les diplômes, les expériences professionnelles, ainsi que tout autre élément dont la vérification pourra être le cas échéant demandée par le Client." },
    { t: "p", x: "Le Sous-Traitant devra produire, sur demande du Client et dans un délai raisonnable ne pouvant excéder 5 jours ouvrés, la preuve que ce contrôle a bien été effectué préalablement à l’arrivée de son personnel dans les locaux du Client. En toutes hypothèses, le Sous-Traitant devra informer sans délai le Client dès qu’il a connaissance d’un élément susceptible de remettre en cause les références de son personnel affecté aux prestations objet du Contrat." },
    { t: "p", x: "La régularité de la situation du personnel du Sous-Traitant au regard du Code du Travail, la régularité de la situation et du paiement des cotisations sociales dues par le Sous-Traitant aux organismes sociaux ainsi que la véracité et l’exactitude des références du personnel mis à disposition par le Sous-Traitant auprès du Client constituent une condition essentielle de la réalisation de la prestation par le Sous-Traitant." },
    { t: "p", x: "Le personnel de chacune des Parties demeure en tout état de cause salarié de ladite partie qui reste redevable des salaires et des charges afférentes. Chaque partie assume, tout au long de l’exécution des missions, la gestion administrative, comptable et sociale de son personnel." },
    { t: "p", x: "Aucune des Parties ne peut prendre un engagement au nom et pour le compte de l’autre. Chaque Partie demeure seule responsable des actes, allégations, engagements, prestations et personnels." },

    { t: "h2", x: "ARTICLE 27 – SOUS-TRAITANCE ET TRANSFERT DU CONTRAT" },
    { t: "p", x: "Le Sous-Traitant doit exécuter lui-même la mission à l’exclusion de toute sous-traitance. Les Services ne pourront être sous-traitées qu’avec l’accord préalable, exprès et écrit du Client. Le Client se réserve le droit de refuser la présence d’un sous-traitant, sans motifs, notamment s’il n’apporte pas les mêmes garanties professionnelles que le Sous-Traitant. Le droit au paiement direct du sous-traitant par le Client est exclu. Les Services fournis par le sous-traitant sont facturés par ce dernier au Sous-Traitant. Le Sous-Traitant est seul garant du respect par le sous-traitant des obligations qu’il a lui-même souscrites vis-à-vis du Client. En cas de manquement au présent article, le Client serait fondé à résilier le Contrat avec le Sous-Traitant de plein droit et sans délai." },
    { t: "p", x: "Le Contrat n’est ni cessible, ni transmissible, en totalité ou partiellement, à quelque titre ou sous quelque modalité que ce soit, y compris par transmission universelle du patrimoine (fusion, scission, apport en nature ou apport partiel d’actif), sauf accord préalable, exprès et écrit du Client." },
    { t: "p", x: "Le Client peut librement céder tout ou partie de ses droits et obligations résultant de la commande à l’une de ses entités affiliées en France." },

    { t: "h2", x: "ARTICLE 28 – DONNÉES PERSONNELLES" },
    { t: "p", x: "Dans la mesure où le Sous-Traitant peut être amené à traiter pour le compte du Client des informations concernant des personnes physiques identifiables (« Données Personnelles »), le Sous-Traitant s’engage à se conformer avec toutes les exigences applicables en matière de protection de données personnelles, y compris le Règlement Général sur la Protection des Données 2016/679 (« RGPD »)." },
    { t: "p", x: "Le Sous-Traitant s’engage notamment à :" },
    { t: "li", x: "traiter les Données Personnelles uniquement pour le compte et conformément aux instructions documentées du Client, aux seules fins de fournir les Services, tout autre traitement des Données Personnelles par le Sous-Traitant étant strictement interdit, à moins qu’un tel traitement ne soit exigé en vertu de la législation de l’Union européenne ou d’un Etat membre applicable au Sous-Traitant ; dans ce cas, le Sous-Traitant devra informer le Client d’une telle exigence légale avant de mettre en œuvre le traitement, sauf si la loi interdit une telle information pour des motifs d’intérêt public importants ;" },
    { t: "li", x: "s’assurer que l’accès aux Données Personnelles est limité aux personnes qui ont besoin d’y avoir accès afin de satisfaire les obligations du Sous-Traitant au titre du Contrat, et que ces personnes autorisées à traiter les Données Personnelles soient soumises à une obligation légale ou contractuelle de confidentialité ;" },
    { t: "li", x: "mettre en œuvre des mesures techniques et organisationnelles appropriées pour protéger les Données Personnelles contre la perte, l’altération, la destruction et le dommage accidentels ou illicites, la divulgation et l’accès non autorisé(e), conformément à l’article 32 du RGPD ; ne pas transférer les Données Personnelles à des sous-traitants, sauf avec un accord préalable, exprès et écrit du Client (comme prévu à l’article 14 du Contrat) et uniquement dans la mesure de ce qui est requis pour la fourniture des Services ; le Sous-Traitant reste entièrement responsable de ses sous-traitants et s’assure contractuellement que ceux-ci soient soumis aux mêmes obligations en matière de protection de données personnelles que celles imposées au Sous-Traitant lui-même par le présent Contrat, notamment en ce qui concerne la mise en œuvre des mesures techniques et organisationnelles ;" },
    { t: "li", x: "selon le choix du Client, supprimer ou renvoyer toutes les Données Personnelles au Client au terme de la prestation de Services et de détruire les copies existantes, à moins que le droit applicable n’exige la conservation de Données Personnelles ;" },
    { t: "li", x: "mettre à la disposition du Client toute information nécessaire pour démontrer le respect des obligations en vertu de ce Contrat et pour permettre la réalisation d’audits, y compris des inspections, par le Client ou un autre auditeur mandaté par le Client, et contribuer à ces audits ; et" },
    { t: "li", x: "informer immédiatement le Client si l’une de ses instructions constitue, selon le Sous-Traitant, une violation du RGPD ou d’autres dispositions applicables relatives à la protection des données." },
    { t: "li", x: "compte tenu de la nature du traitement et des informations à la disposition du Sous-Traitant, aider le Client à garantir le respect de ses obligations en matière de protection de données personnelles, en particulier : (i) de son obligation de donner suite aux demandes des personnes concernées en vue d’exercer leurs droits prévus au chapitre III du RGPD, notamment en mettant en œuvre des mesures techniques et organisationnelles appropriées ; et (ii) de ses obligations prévues aux articles 32 à 36 du RGPD, notamment en notifiant au Client sans délai toute violation de données personnelles dont le Sous-Traitant aura eu connaissance ;" },

    // Fin du corps à deux colonnes — retour pleine largeur pour les signatures et annexes.
    { t: "col2-end" },

    { t: "spacer" },
    { t: "signatures" },

    // ===================== ANNEXE 1 — CONDITIONS PARTICULIERES =====================
    { t: "pagebreak" },
    { t: "annexe-title", x: "ANNEXE 1 — CONDITIONS PARTICULIÈRES AU CONTRAT" },
    { t: "h3", x: "I – DURÉE DU CONTRAT DE PRESTATION" },
    { t: "p", x: "Le présent contrat de prestation est conclu pour la période du {{dateDebut}} au {{dateFin}}." },
    { t: "p", x: "Toute prolongation fera l’objet d’un avenant." },
    { t: "h3", x: "II – CLIENT FINAL" },
    { t: "p", x: "Le nom du client final est {{clientFinal}}." },
    { t: "h3", x: "III – NATURE DES TRAVAUX" },
    { t: "p", x: "Les travaux, placés sous la responsabilité du client concernent les prestations suivantes réalisées par {{consultantNom}}." },
    { t: "p", x: "{{natureTravaux}}" },
    { t: "h3", x: "IV – LIEU D’EXÉCUTION DES TRAVAUX" },
    { t: "p", x: "Les travaux seront exécutés sur le site de {{clientFinal}}, situé à l’adresse suivante : {{lieuExecution}}." },
    { t: "h3", x: "V – PRIX ET MODALITÉS DE PAIEMENT" },
    { t: "p", x: "La prestation sera facturée {{tjm}} € HT / jour." },
    { t: "p", x: "Les factures seront établies mensuellement en fonction des jours réellement consommés et validées par le Compte Rendu d’Activité signé par le client{{craValideParClause}}." },
    { t: "p", x: "Règlement par virement, {{delaiPaiement}} jours, à date de réception de la facture. Les factures seront adressées mensuellement à l’adresse suivante :" },
    { t: "p", x: "Par mail à : {{comptaEmail}}" },
    { t: "p", x: "{{comptaContact}}" },
    { t: "p", x: "{{comptaTel}}" },
    { t: "h3", x: "VI – MODIFICATIONS" },
    { t: "p", x: "Toute modification du contrat fera l’objet d’un avenant signé par les deux parties." },
    { t: "h3", x: "VII – SUIVI DE LA PRESTATION" },
    { t: "p", x: "Dans le cadre du suivi de la prestation, les interlocuteurs désignés sont :" },
    { t: "p", x: "{{bmNom}} — Business Manager - ADBI{{bmEmailClause}}{{bmTelClause}}" },
    { t: "p", x: "et" },
    { t: "p", x: "{{consultantNom}}{{consultantFonctionClause}}{{consultantTelClause}}" },
    { t: "p", x: "Toute modification d’un élément de ce contrat fera objet d’un avenant." },
    { t: "spacer" },
    { t: "signatures" },

    // ===================== ANNEXE — PROPRIETE INTELLECTUELLE =====================
    { t: "pagebreak", opt: "optProprieteAnnexe" },
    { t: "annexe-title", x: "1 — PROPRIÉTÉ INDUSTRIELLE, INTELLECTUELLE ET COMMERCIALE", opt: "optProprieteAnnexe" },
    { t: "p", x: "Le Sous-traitant se réserve le droit d’utiliser les enseignements qu’il aura tirés de l’étude et de la réalisation des travaux qui lui sont confiés par le client final d’ADBI.", opt: "optProprieteAnnexe" },
    { t: "p", x: "Les logiciels et leurs documentations écrits par le prestataire pour un client déterminé deviennent la propriété du client, sauf convention contraire.", opt: "optProprieteAnnexe" },
    { t: "p", x: "Les programmes généraux appartenant au prestataire et qui auront été adaptés aux besoins propres du client, restent la propriété exclusive du client.", opt: "optProprieteAnnexe" },
    { t: "p", x: "Le Sous-traitant bénéficie seulement d’un droit d’utilisation du programme adapté.", opt: "optProprieteAnnexe" },
    { t: "p", x: "Les programmes généraux, dont le prestataire a obtenu un droit de commercialisation et qui auront été adaptés aux besoins propres du client ou mis à sa disposition en l’état, ne deviennent en aucun cas, la propriété du client qui bénéficie seulement d’un droit d’utilisation, dans la limite et selon les conditions stipulées au contrat s’il y a lieu. Le prestataire est autorisé à effectuer pour lui-même, ou à fournir à des tiers des travaux ou services identiques à ceux fournis au titre du présent contrat, et à développer pour lui-même ou pour des tiers des logiciels identiques, similaires ou concurrents de ceux que son personnel effectuera pour le compte du client en vertu du présent contrat.", opt: "optProprieteAnnexe" },

    // ===================== ANNEXE — ANTICORRUPTION =====================
    { t: "pagebreak", opt: "optAnticorruption" },
    { t: "annexe-title", x: "2 — ANTICORRUPTION (LOI SAPIN 2)", opt: "optAnticorruption" },
    { t: "p", x: "Les Parties s'engagent à se conformer pleinement à tout moment aux codes de conduites, lois et règlements applicables, y compris, de manière non exhaustive, les lois en vigueur en matière de lutte contre la corruption et les règles éthiques. En particulier, sous réserve du droit applicable, aucune des Parties ne doit, dans le cadre de l'exécution de leurs obligations respectives en vertu du présent Contrat, payer, promettre ou offrir de payer ou autoriser le paiement de toute somme d'argent ou consentir toute promesse ou offre ou autoriser l'octroi de toute chose de valeur à une Personne chargée d'une fonction publique ou une Entité Publique en vue d'obtenir ou de maintenir une activité, ou d'orienter l'activité vers l'une ou l'autre des Parties (étant entendu que cette Partie et, à sa connaissance, ses salariés et les salariés de ses affiliés n'ont pas directement ou indirectement promis, offert ou fourni tout paiement corrompu, avantage, émolument, pot-de-vin, rétrocession, cadeau ou hospitalité illicites ou autre avantage illégal ou contraire à l'éthique d'une Personne chargée d'une fonction publique ou d'une Entité Publique en relation avec l'exécution des obligations de cette Partie en vertu du présent Contrat, et ne doit pas, directement ou indirectement, s'engager dans l'une des pratiques ci-dessus).", opt: "optAnticorruption" },
    { t: "p", x: "Aux fins des présentes, \"Personne chargée d'une fonction publique\" ou \"Entité Publique\" désigne selon le cas (i) tout dirigeant, salarié, agent, représentant, département, agence, personne chargée de facto de fonctions publiques, personne morale, division ou subdivision de l'Etat ou toute organisation militaire ou internationale, y compris, de manière non exhaustive, de tout ministère ou d'une entreprise publique ou société affiliée, ou (ii) tout candidat à un mandat politique, parti politique ou agent d'un parti politique.", opt: "optAnticorruption" },
    { t: "p", x: "Le Prestataire déclare, et garantit, dans le cadre de l’exécution du présent contrat ou de toute stipulation découlant de celui-ci ou en relation avec celui-ci : a) qu’il se conforme aux Lois Anticorruption applicables, et b) qu’il n’a pas offert et n’offrira aucun avantage à une personne dépositaire de l’autorité publique, chargée d’une mission de service public ou investie d’un mandat électif public ou un agent public (tel que défini par chaque pays selon sa propre législation ou par l’OCDE) en violation des Lois Anticorruption applicables, et c) qu’il n’a pas promis, offert ou accordé et qu’il ne proposera pas ni n’offrira ni n’accordera aucun avantage à toute personne ou toute entité, en violation des Lois Anticorruption applicables, et d) qu’il n’a pas sollicité et ne sollicitera pas directement ou indirectement par l’intermédiaire d’une personne ou d’une entité morale, toute action ou abstention d’action en violation des lois Anti-Corruption applicables ; e) qu’il n’a pas sollicité et ne sollicitera pas, directement ou indirectement un avantage indu en violation des Lois Anticorruption ; f) qu’il a formé, et continuera à former, ses employés à la prévention de la corruption.", opt: "optAnticorruption" },
    { t: "p", x: "On entend par « Lois Anticorruption », toute loi, règlement, règlementation et autres dispositions juridiquement contraignantes relatifs à la corruption, au blanchiment de capitaux, à la fraude ou à toutes infractions du même ordre. Nonobstant tout recours expressément stipulé au Contrat, ou tout autre droit ou recours prévu en droit ou en équité, le Client aura le droit de prendre toute mesure qu’il estimera appropriée, y compris le droit de mettre fin au contrat avec effet immédiat et/ou d’initier toute procédure judiciaire, en cas de non-respect du présent article (anti-corruption) par le Prestataire ou si celui-ci commet un acte de corruption avéré. Aucune indemnisation ne sera due au Prestataire pour toute perte, dommage, qui résulterait de la résiliation du Contrat dans ce cadre. Le Sous-Traitant doit informer sans délai ADBI dans le cas où il ferait l’objet d’une enquête ou d’une investigation liée au non-respect des Lois Anticorruption. Le Client (ou la société d’audit nommée par celui-ci) aura la possibilité de diligenter un audit de conformité du Sous-traitant à tout moment, et ce, même sans préavis, pour s’assurer que celui-ci se conforme aux obligations anti-corruption.", opt: "optAnticorruption" },

    // ===================== ANNEXE — PROTECTION DES DONNEES (RGPD) =====================
    { t: "pagebreak", opt: "optRgpd" },
    { t: "annexe-title", x: "3 — PROTECTION DES DONNÉES À CARACTÈRE PERSONNEL", opt: "optRgpd" },
    { t: "p", x: "Dans le cas d’un traitement de données à caractère personnel du Client Final par le « Sous-traitant d’ADBI » par le présent Contrat, les Parties reconnaissent que le Client Final {{clientFinal}} est le Responsable de Traitement et que {{stNom}} est le Sous-traitant d’ADBI de données à caractère personnel et s’engagent à se conformer aux lois applicables en matière de données personnelles. Le Client Final autorise le Sous-traitant d’ADBI à traiter lesdites données personnelles en son nom et pour son compte lorsque cela est nécessaire pour l’accomplissement de l’objet du Contrat.", opt: "optRgpd" },
    { t: "p", x: "Dans le cadre de leurs relations contractuelles, les Parties s’engagent à respecter la réglementation en vigueur applicable au traitement de données à caractère personnel et, en particulier, le règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016 applicable depuis le 25 mai 2018 (ci-après, « le RGPD »).", opt: "optRgpd" },
    { t: "h3", x: "1. Caractéristiques du traitement", opt: "optRgpd" },
    { t: "p", x: "**Finalité** — Le Sous-traitant d’ADBI est autorisé à traiter pour le compte du Responsable de Traitement les données à caractère personnel nécessaires pour fournir le ou les service(s) décrits dans le contrat réf : Contrat de prestation ADBI {{stNom}}.", opt: "optRgpd" },
    { t: "p", x: "**Personnes concernées** — Les données personnelles concernent les catégories de personnes concernées suivantes :", opt: "optRgpd" },
    { t: "table", opt: "optRgpd", headers: ["Catégories de Personnes Concernées", "Barrer si non applicable"], rows: [
      ["Clients et prospects", "Oui"],
      ["(candidats) et (anciens) employés et stagiaires", "Oui"],
      ["(potentiels)/(anciens) fournisseurs", "Oui"],
      ["(potentiels)/(anciens) partenaires commerciaux", "Oui"],
    ] },
    { t: "p", x: "**Catégories de données personnelles** — Les données personnelles concernent les catégories de données personnelles suivantes :", opt: "optRgpd" },
    { t: "table", opt: "optRgpd", headers: ["Catégories de Données Personnelles", "Barrer si non applicable"], rows: [
      ["Noms d’utilisateurs, mots de passe et toute autre donnée de connexion.", "Oui"],
      ["Données de communication (c’est-à-dire nom, adresse, titre, poste, téléphone, adresse e-mail, etc.)", "Oui"],
    ] },
    { t: "p", x: "**Catégories particulières de données personnelles (le cas échéant)** — Les données personnelles n’incluent pas de données sensibles au sens de la réglementation applicable.", opt: "optRgpd" },
    { t: "h3", x: "2. Obligations du Sous-traitant à l’égard du Responsable de traitement", opt: "optRgpd" },
    { t: "p", x: "2.1. Le Sous-traitant s'engage à :", opt: "optRgpd" },
    { t: "li", x: "Traiter les données uniquement pour la ou les seule(s) finalité(s) qui fait/font l’objet de la sous-traitance,", opt: "optRgpd" },
    { t: "li", x: "Traiter les données conformément aux instructions documentées du responsable de traitement figurant en annexe du présent contrat. Si le Sous-traitant considère qu’une instruction constitue une violation du RGPD ou de toute autre disposition du droit de l’Union ou du droit des Etats membres relative à la protection des données, il en informe immédiatement le responsable de traitement. En outre, si le Sous-traitant est tenu de procéder à un transfert de données vers un pays tiers ou à une organisation internationale, en vertu du droit de l’Union ou du droit de l’Etat membre auquel il est soumis, il doit informer le Responsable du traitement de cette obligation juridique avant le traitement, sauf si le droit concerné interdit une telle information pour des motifs importants d'intérêt public,", opt: "optRgpd" },
    { t: "li", x: "Garantir la confidentialité des données à caractère personnel traitées dans le cadre du présent Contrat,", opt: "optRgpd" },
    { t: "li", x: "Veiller à ce que les personnes autorisées à traiter les données à caractère personnel en vertu du présent contrat s’engagent à respecter la confidentialité ou soient soumises à une obligation légale appropriée de confidentialité et reçoivent la formation nécessaire en matière de protection des données à caractère personnel,", opt: "optRgpd" },
    { t: "li", x: "Prendre en compte, s’agissant de ses outils, produits, applications ou services, les principes de protection des données dès la conception et de protection des données par défaut.", opt: "optRgpd" },
    { t: "p", x: "2.2. Information des personnes concernées — Le sous-traitant, au moment de la collecte des données, doit fournir aux personnes concernées par les opérations de traitement l’information relative aux traitements de données qu’il réalise. Dans la mesure du possible, le sous-traitant doit aider le responsable de traitement à s’acquitter de son obligation de donner suite aux demandes d’exercice des droits des personnes concernées : droit d’accès, de rectification, d’effacement et d’opposition, droit à la limitation du traitement, droit à la portabilité des données, droit de ne pas faire l’objet d’une décision individuelle automatisée (y compris le profilage). Lorsque les personnes concernées exercent auprès du sous-traitant des demandes d’exercice de leurs droits, le sous-traitant doit adresser ces demandes dès réception au client.", opt: "optRgpd" },
    { t: "p", x: "2.3. Notification des violations de données — Le sous-traitant notifie au responsable de traitement toute violation de données à caractère personnel dans les meilleurs délais après en avoir pris connaissance et par courriel avec accusé de réception. Cette notification est accompagnée de toute documentation utile afin de permettre au responsable de traitement, si nécessaire, de notifier cette violation à l’autorité de contrôle compétente.", opt: "optRgpd" },
    { t: "p", x: "2.6. Mesures de sécurité — Le Sous-traitant s’engage à mettre en œuvre des mesures techniques et organisationnelles appropriées afin de garantir la sécurité des données personnelles traitées ainsi que les droits et libertés des personnes concernées par ce traitement.", opt: "optRgpd" },
    { t: "p", x: "2.7. Sort des données — Au terme de la prestation de services relatifs au traitement de ces données, le sous-traitant s’engage à, au choix du Client : détruire toutes les données à caractère personnel ou les renvoyer au Responsable de traitement ou les renvoyer au sous-traitant désigné par le responsable de traitement. Le renvoi doit s’accompagner de la destruction de toutes les copies existantes dans les systèmes d’information du Sous-traitant. Une fois détruites, le Sous-traitant doit justifier par écrit de la destruction.", opt: "optRgpd" },
    { t: "p", x: "2.10. Documentation — Le Sous-traitant met à la disposition du Responsable de traitement la documentation nécessaire pour démontrer le respect de toutes ses obligations et pour permettre la réalisation d'audits, y compris des inspections, par le responsable du traitement ou un autre auditeur qu'il a mandaté, et contribuer à ces audits.", opt: "optRgpd" },
    { t: "h3", x: "3. Obligations du responsable de traitement vis-à-vis du Sous-traitant", opt: "optRgpd" },
    { t: "p", x: "Le Responsable de traitement s’engage à fournir au sous-traitant les données visées au II des présentes clauses et à veiller, au préalable et pendant toute la durée du traitement, au respect des obligations prévues par le RGPD de la part du Sous-traitant.", opt: "optRgpd" },
  ],
};

// ===================== AVENANT AU CONTRAT DE PRESTATION =====================
// Reprend la structure complète d'av2 (en-tête AVENANT N°, parties, Annexe 1
// description/durée des prestations, signatures) + un article « Objet de
// l'avenant » qui référence explicitement le contrat initial (n° + date).
// Pas de couverture : l'en-tête encadré apparaît dès la 1re page (headerOnFirst).
const avenant = {
  id: "avenant",
  titre: "AVENANT AU CONTRAT",
  headerTitle: "AVENANT N° {{numeroAvenant}} — {{contratTypeLabelShort}}",
  headerNum: "Contrat N° : {{numeroContratInitial}}",
  footerText: "Avenant — {{contratTypeLabelShort}} — Contrat n° {{numeroContratInitial}}",
  headerOnFirst: true,
  blocks: [
    // ---- Parties (désignations adaptées au type de contrat initial) ----
    { t: "p", x: "**ENTRE LES SOUSSIGNÉS :**" },
    { t: "p", x: "**{{avPartie1Nom}}**, représentée par {{avPartie1Repr}}{{avPartie1QualiteClause}}, dûment habilité(e) à signer les présentes." },
    { t: "p", x: "Ci-après désignée « {{avDesignation1}} », d’une part." },
    { t: "spacer" },
    { t: "p", x: "**ET**" },
    { t: "p", x: "**{{avPartie2Nom}}**, représentée par {{avPartie2Repr}}{{avPartie2QualiteClause}}, dûment habilité(e) à signer les présentes." },
    { t: "p", x: "Ci-après désignée « {{avDesignation2}} », d’autre part." },
    { t: "spacer" },

    { t: "h3", x: "ARTICLE 1 – OBJET DE L’AVENANT" },
    { t: "p", x: "Le présent avenant se rapporte à {{contratTypeLabelDef}} n° {{numeroContratInitial}}, conclu(e) le {{dateContratInitial}} entre les Parties (ci-après « le Contrat initial »)." },
    { t: "p", x: "Il a pour objet : {{objetAvenant}}." },
    { t: "spacer" },

    { t: "h3", x: "ARTICLE 2 – MAINTIEN DES CONDITIONS" },
    { t: "p", x: "Toutes les autres stipulations du Contrat initial et de ses annexes, non modifiées par le présent avenant, demeurent inchangées et pleinement applicables." },
    { t: "p", x: "Le présent avenant prend effet à compter du {{dateEffet}}." },
    { t: "spacer" },

    { t: "signatures",
      leftTitle: "Pour {{avDesignation1}} — {{avPartie1Nom}}",
      leftName: "{{avPartie1Repr}}",
      leftSub: "{{avPartie1QualiteLine}}",
      rightTitle: "Pour {{avDesignation2}} — {{avPartie2Nom}}",
      rightName: "{{avPartie2Repr}}",
      rightSub: "{{avPartie2QualiteLine}}" },
  ],
};

// ===================== CDS — CENTRE DE SERVICES (ADBI = PRESTATAIRE) =====================
// Transcription verbatim du modèle « Contrat de prestations informatiques du centre de
// services ». Ici ADBI est le PRESTATAIRE (fixe : M. Cédric HOUPE, Directeur des Opérations)
// et l'autre partie est LE CLIENT (variables). En-tête dès la 1re page (pas de couverture).
const cds = {
  id: "cds",
  titre: "CONTRAT DE PRESTATIONS INFORMATIQUES — CENTRE DE SERVICES",
  headerTitle: "CONTRAT DE PRESTATIONS INFORMATIQUES — CENTRE DE SERVICES",
  headerNum: "Contrat N° : {{numeroContrat}}",
  footerText: "Contrat de prestations informatiques — Centre de services — N° {{numeroContrat}}",
  headerOnFirst: true,
  blocks: [
    // ---- Parties ----
    { t: "p", x: "**ENTRE LES SOUSSIGNÉS :**" },
    { t: "p", x: "**{{clientNom}}** — {{clientFormeJuridique}}" },
    { t: "p", x: "{{clientAdresse}} — Capital : {{clientCapital}} — {{clientRcs}} — Numéro TVA Intracommunautaire : {{clientTva}}" },
    { t: "p", x: "Représentée par : {{clientSignataireNom}}, agissant en qualité de {{clientSignataireFonction}}, dûment habilité à signer les présentes." },
    { t: "p", x: "Ci-après désignée le « LE CLIENT », d’une part." },
    { t: "spacer" },
    { t: "p", x: "**ET**" },
    { t: "p", x: "**ADBI** — SAS" },
    { t: "p", x: "5 Rue du Banquier 75013 Paris — Capital : 250 000 € — RCS Paris n° 805 321 650 — TVA Intracom FR 27 805321650" },
    { t: "p", x: "Représentée par : Monsieur Cédric HOUPE, agissant en qualité de Directeur des Opérations, dûment habilité à signer les présentes." },
    { t: "p", x: "Ci-après désignée « PRESTATAIRE », d’autre part." },
    { t: "spacer" },

    { t: "h3", x: "Préambule" },
    { t: "p", x: "Le Client, spécialisé dans le domaine de {{clientDomaine}}, souhaite bénéficier des services du Prestataire pour la réalisation de prestations en matière de développement informatique, de maintenance corrective et évolutive (MCO), et de support technique. Le Prestataire, fort de son expertise reconnue dans ces domaines, est disposé à fournir ces prestations selon les modalités définies ci-après." },
    { t: "p", x: "**Il a été convenu ce qui suit :**" },

    { t: "h2", x: "ARTICLE 1 – OBJET DU CONTRAT" },
    { t: "p", x: "Le présent contrat a pour objet de définir les conditions dans lesquelles le prestataire fournira au Client des prestations de services. Ce contrat porte sur plusieurs modes d’intervention, pouvant être combinés :" },
    { t: "p", x: "**Mode Centre de service :** Engagement de moyen allié à des engagements de délai de prise en charge permettant la prise en charge de prestations variées (projet et TMA/MCO) avec une flexibilité permettant la continuité de services malgré des phases d’activité discontinues." },
    { t: "p", x: "**Mode Projet en Régie :** Engagement de moyen avec la mise à disposition de ressources humaines pour la réalisation de projets sous la supervision du Client, avec une facturation au temps passé." },

    { t: "h2", x: "ARTICLE 2 – MODE CENTRE DE SERVICES" },
    { t: "h3", x: "2.1. Description" },
    { t: "p", x: "Le Centre de services a pour objectif de répondre aux besoins de plusieurs clients en simultané. Ceci permet une flexibilité sur les interventions puisque le Prestataire peut activer le centre de services à sa convenance, tant sur la temporalité que sur le périmètre des actions à effectuer." },
    { t: "h3", x: "2.2. Modalités de la Prestation" },
    { t: "li", x: "Le centre de Services a pour vocation à recevoir des demandes et non à vérifier constamment les actions à mener." },
    { t: "li", x: "Une souscription avec un engagement de 12 mois inclut 40h du Centre de Services à consommer chaque mois." },
    { t: "li", x: "Ces 40 heures mensuelles ne sont pas reportables sur le mois suivant." },
    { t: "li", x: "La souscription peut être complétée par des heures supplémentaires achetées par pack." },
    { t: "li", x: "Ces heures dans les packs ont une durée de validité de 365 jours et ne sont pas reportables sur l’année suivante." },
    { t: "li", x: "Un responsable et un expert technique du Centre de Services (CDS) sont en support." },
    { t: "li", x: "L’unité indivisible de traitement est de 1 heure." },
    { t: "li", x: "Période de couverture par défaut : de 9h à 13h puis de 14h à 18h du lundi au vendredi (une alternance est cependant appliquée pendant la pause méridienne)." },
    { t: "h3", x: "2.3. Engagements" },
    { t: "li", x: "Engagement de moyen." },
    { t: "li", x: "Prise en charge de la demande en 1 jour ouvré." },
    { t: "h3", x: "2.4. Tarification" },
    { t: "p", x: "Souscription mensuelle au service : {{mntSouscription}} € HT avec un engagement annuel." },
    { t: "p", x: "Packs annuels complémentaires disponibles :" },
    { t: "li", x: "Pack de 40 heures : {{pack40}} € HT" },
    { t: "li", x: "Pack de 80 heures : {{pack80}} € HT" },
    { t: "li", x: "Pack de 200 heures : {{pack200}} € HT" },
    { t: "li", x: "Pack de 400 heures : {{pack400}} € HT" },
    { t: "p", x: "Cette tarification est révisable chaque année." },
    { t: "h3", x: "2.5. Conditions de Paiement" },
    { t: "li", x: "Paiement mensuel pour la souscription." },
    { t: "li", x: "Paiement des packs à échoir." },

    { t: "h2", x: "ARTICLE 3 – MODE PROJET EN RÉGIE" },
    { t: "h3", x: "3.1. Description" },
    { t: "p", x: "Afin de répondre aux demandes du client, un consultant intègre l’équipe client. Il appartient au Client de confier et suivre des tâches de réalisation." },
    { t: "h3", x: "3.2. Modalités de la Prestation" },
    { t: "li", x: "Réalisation du projet supervisée par le Client." },
    { t: "li", x: "Plusieurs profils peuvent intervenir : Consultant, Expert Technique." },
    { t: "h3", x: "3.3. Engagements" },
    { t: "li", x: "Engagement de moyen." },
    { t: "li", x: "Des profils sont soumis à validation du Client sous 5 à 8 jours ouvrés." },
    { t: "h3", x: "3.4. Tarification" },
    { t: "p", x: "Facturation au temps passé selon les TJM suivants :" },
    { t: "li", x: "Expert Technique : {{tjmExpert}} € HT" },
    { t: "li", x: "Consultant CDS : {{tjmConsultant}} € HT" },
    { t: "h3", x: "3.5. Conditions de Paiement" },
    { t: "li", x: "Facturation au temps passé sur la base d’un compte rendu d’activité mensuel." },
    { t: "li", x: "Paiement à 45 jours fin de mois." },

    { t: "h2", x: "ARTICLE 4 – FRAIS DE DÉPLACEMENT" },
    { t: "p", x: "Les frais réels pour la venue sur site du Client seront à la charge du Client sur la base de présentation des justificatifs. Les frais éligibles sont :" },
    { t: "li", x: "Transport : Billets de train (classe standard), billets d’avion (classe économique), frais de kilométrage selon le barème fiscal en vigueur, parking." },
    { t: "li", x: "Hébergement : Hôtel de catégorie 3 étoiles minimum." },
    { t: "li", x: "Restauration : Repas pris lors des déplacements." },
    { t: "p", x: "Les déplacements respectent les règles suivantes : suivant la distance, une arrivée la veille peut être faite pour être sur place tôt le jour de la prestation ; toute nuit passée à l’hôtel induit un dîner." },
    { t: "p", x: "Si des plafonds sont fixés par le Client, ceux-ci doivent être fournis avant la signature de ce contrat afin de vérifier leur compatibilité. Le Prestataire s’engage à optimiser les coûts et à privilégier les solutions les plus économiques." },
    { t: "p", x: "**Accords Préalables :** Pour des frais exceptionnels ou dépassant les plafonds définis, une approbation écrite du Client est requise avant engagement." },
    { t: "p", x: "Dans le cas d’une annulation ou du report par le Client d’une intervention sur site, tous les frais engagés n’ayant pas pu être remboursés seront facturés au Client." },

    { t: "h2", x: "ARTICLE 5 – HEURES SUPPLÉMENTAIRES, ASTREINTES" },
    { t: "h3", x: "5.1. Définitions" },
    { t: "p", x: "Une heure supplémentaire désigne une période entre 20h et 8h. Les périodes entre 8h et 9h puis entre 19h et 20h peuvent être considérées comme des heures supplémentaires si elles sont récurrentes ou si elles sont combinées. À partir de 5 minutes, une heure complète est prise en compte." },
    { t: "p", x: "L’astreinte désigne une période durant laquelle un collaborateur, sans être sur son lieu de travail, doit rester disponible pour intervenir en cas de besoin, généralement dans un délai rapide. Pendant cette période, le collaborateur n’est pas forcément en activité mais doit pouvoir être contacté et se tenir prêt à accomplir une tâche si cela s’avère nécessaire. Une astreinte est dite « activée » si une tâche doit être réalisée." },
    { t: "h3", x: "5.2. Prévenance" },
    { t: "p", x: "Dans le cas des heures supplémentaires prévisibles, le Client s’engage à en informer au plus tôt le Collaborateur ainsi que le responsable commercial du Prestataire. Suivant le mode de prestation, il appartient au Prestataire de confirmer la présence du collaborateur." },
    { t: "p", x: "Dans le cas des heures supplémentaires non-prévisibles, le Client et/ou le Collaborateur s’engage à en informer au plus tôt le responsable commercial du Prestataire. Le Collaborateur doit faire de son mieux pour répondre favorablement à cette demande de disponibilité." },
    { t: "h3", x: "5.3. Tarification" },
    { t: "table", headers: ["Heures supplémentaires", "Majoration"], rows: [
      ["Semaine entre 19h et 21h", "150% du TJM"],
      ["Semaine entre 21h et 7h", "175% du TJM"],
      ["Semaine entre 7h et 9h", "150% du TJM"],
      ["Samedi entre 9h et 19h", "150% du TJM"],
      ["Samedi entre 19h et 21h", "175% du TJM"],
      ["Samedi entre 21h et 0h", "200% du TJM"],
      ["Samedi entre 7h et 9h", "200% du TJM"],
      ["Dimanche entre 10h et 18h", "200% du TJM"],
      ["Dimanche avant 10h et après 18h", "300% du TJM"],
    ] },
    { t: "spacer" },
    { t: "table", headers: ["Astreintes du week-end", "Majoration"], rows: [
      ["Forfait astreinte ½ journée (activée ou non)", "33% du TJM"],
      ["Activation astreinte entre 1h et 8h", "150% du TJM"],
      ["Activation astreinte plus de 8h", "175% du TJM"],
      ["Dimanche entre 10h et 18h", "200% du TJM"],
    ] },

    { t: "h2", x: "ARTICLE 6 – RÉVISION DES PRIX" },
    { t: "dash", x: "Périodicité : Les tarifs peuvent être révisés annuellement, à la date anniversaire du contrat pour la souscription annuelle, par année civile pour les packs d’heures complémentaires." },
    { t: "dash", x: "Indice de Référence : La révision est basée sur l’évolution de l’indice Syntec publié par la Fédération Syntec et d’une augmentation fixe complémentaire." },
    { t: "dash", x: "Calcul de la Révision : Nouveau tarif = Tarif initial × ((Indice N / Indice N-1) + 0,06), où Indice N = dernier indice connu à la date de révision et Indice N-1 = indice connu lors de la précédente révision ou à la date de signature du contrat." },
    { t: "dash", x: "Notification : Le Prestataire notifie le Client par écrit (email ou courrier recommandé) au moins deux mois avant l’application des nouveaux tarifs." },
    { t: "dash", x: "Acceptation : En l’absence de contestation écrite du Client dans un délai d’un mois après la notification, les nouveaux tarifs sont considérés comme acceptés." },

    { t: "h2", x: "ARTICLE 7 – OBLIGATIONS DU PRESTATAIRE" },
    { t: "h3", x: "7.1. Qualité des Services" },
    { t: "dash", x: "Professionnalisme : Le Prestataire s’engage à réaliser les prestations avec diligence, compétence et professionnalisme, conformément aux normes en vigueur et aux meilleures pratiques du secteur." },
    { t: "dash", x: "Conformité : Les prestations seront conformes aux spécifications convenues avec le Client." },
    { t: "h3", x: "7.2. Ressources Humaines" },
    { t: "dash", x: "Qualification du Personnel : Le Prestataire garantit que les intervenants affectés aux prestations disposent des compétences et de l’expérience requises." },
    { t: "dash", x: "Formation Continue : Le Prestataire s’engage à assurer la formation continue de ses collaborateurs pour maintenir un haut niveau de compétence." },
    { t: "h3", x: "7.3. Confidentialité" },
    { t: "dash", x: "Engagement : Le Prestataire s’engage à respecter la confidentialité de toutes les informations, documents, données, dont il pourrait avoir connaissance dans le cadre de l’exécution du contrat." },
    { t: "dash", x: "Durée : L’obligation de confidentialité perdure pendant toute la durée du contrat et pendant une période de cinq ans après son expiration ou sa résiliation." },
    { t: "dash", x: "Exceptions : Ne sont pas considérées comme confidentielles les informations tombées dans le domaine public sans faute du Prestataire, déjà connues du Prestataire avant leur communication par le Client, ou obtenues de tiers de manière licite." },
    { t: "h3", x: "7.4. Assurance" },
    { t: "dash", x: "Responsabilité Civile Professionnelle : Le Prestataire déclare être assuré auprès d’Axa au titre de sa responsabilité civile professionnelle, pour des montants suffisants pour couvrir les risques liés à l’exécution du contrat." },
    { t: "dash", x: "Justificatifs : Le Prestataire fournira au Client, sur demande, une attestation d’assurance en cours de validité." },

    { t: "h2", x: "ARTICLE 8 – OBLIGATIONS DU CLIENT" },
    { t: "h3", x: "8.1. Collaboration" },
    { t: "dash", x: "Informations nécessaires : Le Client s’engage à fournir au Prestataire toutes les informations, documents, accès et moyens nécessaires à la bonne exécution des prestations." },
    { t: "dash", x: "Décisions et Validations : Le Client prend les décisions requises et valide les documents, rapports, livrables dans les délais convenus, afin de ne pas retarder l’avancement des prestations." },
    { t: "h3", x: "8.2. Ressources" },
    { t: "dash", x: "Accès aux Locaux : Le Client assure l’accès aux locaux, équipements, infrastructures nécessaires pour le personnel du Prestataire." },
    { t: "dash", x: "Matériels et Logiciels : Le Client met à disposition les matériels, logiciels, licences nécessaires à l’exécution des prestations, sauf disposition contraire." },
    { t: "h3", x: "8.3. Confidentialité" },
    { t: "dash", x: "Engagement : Le Client s’engage à respecter la confidentialité des méthodes, savoir-faire, outils, documents du Prestataire." },
    { t: "dash", x: "Protection des Données : Le Client est responsable du respect de la réglementation relative à la protection des données personnelles (RGPD) pour les données qu’il confie au Prestataire." },

    { t: "h2", x: "ARTICLE 9 – PROPRIÉTÉ INTELLECTUELLE" },
    { t: "h3", x: "9.1. Projets en Régie et Expertise Sénior" },
    { t: "dash", x: "Licence d’Utilisation : Le Prestataire accorde au Client une licence non exclusive, non transférable, pour utiliser les livrables dans le cadre de son activité interne." },
    { t: "dash", x: "Réutilisation par le Prestataire : Le Prestataire conserve le droit de réutiliser les méthodes, savoir-faire, connaissances acquises ou développées lors des prestations, sous réserve du respect de la confidentialité." },
    { t: "h3", x: "9.2. Garanties" },
    { t: "dash", x: "Garantie d’Éviction : Le Prestataire garantit que les livrables ne portent pas atteinte aux droits de propriété intellectuelle de tiers." },

    { t: "h2", x: "ARTICLE 10 – RESPONSABILITÉ" },
    { t: "h3", x: "10.1. Limitation de Responsabilité" },
    { t: "dash", x: "Plafond de Responsabilité : La responsabilité totale du Prestataire, tous dommages confondus, est limitée au montant total des sommes perçues au titre du contrat au cours des six derniers mois." },
    { t: "dash", x: "Exclusion des Dommages Indirects : Le Prestataire ne pourra être tenu responsable des dommages indirects subis par le Client, tels que perte de chiffre d’affaires, perte de données, perte d’exploitation, préjudice commercial." },
    { t: "h3", x: "10.2. Force Majeure" },
    { t: "dash", x: "Définition : Constitue un cas de force majeure tout événement extérieur, imprévisible, irrésistible au sens de l’article 1218 du Code civil, rendant impossible l’exécution des obligations." },
    { t: "dash", x: "Effets : En cas de force majeure, l’exécution des obligations est suspendue pendant la durée de l’événement. Si la durée excède trois mois, chaque Partie peut résilier le contrat de plein droit." },
    { t: "dash", x: "Obligations des Parties : La Partie affectée par la force majeure doit informer l’autre Partie par écrit dès que possible, et fournir les justificatifs appropriés." },

    { t: "h2", x: "ARTICLE 11 – DURÉE DU CONTRAT" },
    { t: "dash", x: "Entrée en Vigueur : Le contrat entre en vigueur à la date de sa signature par les deux Parties." },
    { t: "dash", x: "Durée Initiale : Le contrat est conclu pour une durée déterminée d’un an, à compter de la date d’entrée en vigueur." },
    { t: "dash", x: "Renouvellement : À l’expiration de la durée initiale, le contrat est renouvelé par tacite reconduction pour des périodes successives d’un an, sauf dénonciation par l’une des Parties." },
    { t: "dash", x: "Modalités de Dénonciation : La Partie souhaitant ne pas renouveler le contrat doit notifier sa décision par lettre recommandée avec accusé de réception, au moins trois mois avant l’échéance." },

    { t: "h2", x: "ARTICLE 12 – RÉSILIATION" },
    { t: "h3", x: "12.1. Résiliation pour Faute" },
    { t: "dash", x: "Manquement Grave : En cas de manquement grave par l’une des Parties à ses obligations essentielles, l’autre Partie peut résilier le contrat de plein droit, 30 jours après une mise en demeure restée infructueuse." },
    { t: "dash", x: "Notification : La mise en demeure doit préciser le manquement reproché et indiquer la volonté de résilier le contrat en l’absence de remédiation." },
    { t: "h3", x: "12.2. Résiliation pour Convenance du mode Régie" },
    { t: "dash", x: "Préavis : Chaque Partie peut résilier les prestations en Régie à tout moment, avec un préavis de trois mois, notifié par lettre recommandée avec accusé de réception." },
    { t: "dash", x: "Conséquences : Les prestations engagées jusqu’à la date effective de résiliation sont dues par le Client. Le Prestataire s’engage à assurer une transition afin de ne pas pénaliser le Client." },

    { t: "h2", x: "ARTICLE 13 – DISPOSITIONS GÉNÉRALES" },
    { t: "h3", x: "13.1. Intégralité du Contrat" },
    { t: "dash", x: "Documents Contractuels : Le contrat et ses annexes constituent l’intégralité de l’accord entre les Parties et remplacent tout accord antérieur, écrit ou verbal." },
    { t: "dash", x: "Hiérarchie des Documents : En cas de contradiction, les stipulations du contrat prévalent sur celles des annexes." },
    { t: "h3", x: "13.2. Modifications" },
    { t: "dash", x: "Avenants : Toute modification du contrat doit faire l’objet d’un avenant écrit, signé par les deux Parties." },
    { t: "h3", x: "13.3. Nullité Partielle" },
    { t: "dash", x: "Clause Nulle : Si une ou plusieurs stipulations du contrat sont déclarées nulles ou inapplicables, les autres stipulations restent en vigueur. Les Parties s’efforceront de remplacer la clause nulle par une clause valide ayant un effet économique équivalent." },
    { t: "h3", x: "13.4. Cession du Contrat" },
    { t: "dash", x: "Interdiction de Cession : Le contrat ne peut être cédé ou transféré, en tout ou partie, par l’une des Parties sans l’accord préalable écrit de l’autre Partie." },
    { t: "h3", x: "13.5. Notifications" },
    { t: "dash", x: "Forme des Notifications : Toute notification ou communication entre les Parties doit être effectuée par écrit, soit par courrier recommandé avec accusé de réception, soit par email avec accusé de réception électronique." },

    { t: "h2", x: "ARTICLE 14 – PERSONNEL" },
    { t: "p", x: "Chaque partie s’engage vis-à-vis de l’autre, à ne pas débaucher, embaucher ou faire travailler de manière directe et indirecte, toute personne ayant participé à la réalisation des travaux demandés, pendant toute la durée du contrat et un an à compter de la cessation des relations contractuelles définies par les présentes et leurs avenants." },
    { t: "p", x: "En cas d’infraction à la présente interdiction, la partie défaillante sera tenue de payer immédiatement à l’autre Partie, à titre de clause pénale, une indemnité forfaitaire d’un montant égal au montant brut des appointements perçus au cours des six (6) derniers mois par la personne embauchée." },

    { t: "h2", x: "ARTICLE 15 – SUIVI DES PRESTATIONS" },
    { t: "p", x: "Dans le cadre du suivi des prestations TMA/Régie, les interlocuteurs désignés sont :" },
    { t: "p", x: "**Suivi Opérationnel :** Monsieur Cédric HOUPE — Directeur des Opérations - ADBI — choupe@adbi.fr — 06 64 93 97 99" },
    { t: "p", x: "**Suivi Commercial :** Monsieur Cédric HOUPE — Directeur des Opérations - ADBI — choupe@adbi.fr — 06 64 93 97 99" },
    { t: "p", x: "et" },
    { t: "p", x: "**{{clientSuiviNom}}** — {{clientSuiviFonction}} — {{clientSuiviEmail}} — {{clientSuiviTel}}" },

    { t: "h2", x: "ARTICLE 16 – LOI APPLICABLE ET JURIDICTION COMPÉTENTE" },
    { t: "dash", x: "Loi Applicable : Le contrat est régi par le droit français." },
    { t: "dash", x: "Règlement des Litiges : En cas de différend, les Parties s’efforceront de le résoudre à l’amiable dans un délai de 30 jours à compter de la notification du différend. À défaut d’accord amiable, les Parties peuvent recourir à une médiation conformément au règlement de médiation du CMAP (Centre de Médiation et d’Arbitrage de Paris)." },
    { t: "dash", x: "Attribution de Juridiction : En cas d’échec de la médiation, tout litige sera soumis à la compétence exclusive des tribunaux du ressort de la Cour d’Appel de Paris, y compris en cas de référé, d’appel en garantie ou de pluralité de défendeurs." },

    { t: "spacer" },
    { t: "signatures",
      leftTitle: "Pour le Client — {{clientNom}}",
      leftName: "{{clientSignataireNom}}",
      leftSub: "{{clientSignataireQualiteClause}}",
      rightTitle: "Pour ADBI",
      rightName: "Monsieur Cédric HOUPE",
      rightSub: "En qualité de : Directeur des Opérations" },
  ],
};

// Stubs pour CDI / CDD (a completer quand Amine fournira les modeles)
const cdi = { id: "cdi", titre: "CONTRAT DE TRAVAIL À DURÉE INDÉTERMINÉE (CDI)", stub: true, blocks: [] };
const cdd = { id: "cdd", titre: "CONTRAT DE TRAVAIL À DURÉE DÉTERMINÉE (CDD)", stub: true, blocks: [] };

const TEMPLATES = { "sous-traitance": sousTraitance, avenant, cds, cdi, cdd };

module.exports = { TEMPLATES, sousTraitance };
